In [1]:
import numpy as np
import librosa as lb
import pickle
from model_SVM import *

In [2]:
data = ManageData()
data.LoadTrainData()

Training data loaded!
Example:
X: [-0.00052149 -0.00028545  0.00055002 ... -0.00323435 -0.00400418
  0.        ] 
y: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
data.LoadValidationData()

Validation data loaded!
Example:
X: [0.         0.         0.         ... 0.12279464 0.10125782 0.08570299] 
y: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [4]:
data.MakeFeatures()

Features made!
Example:
X_train: [0.02515266 0.02506739 0.01922597 ... 0.00595387 0.00499306 0.00392525] X_val:
 [0.         0.         0.         ... 0.09469496 0.08440389 0.06921414]


In [ ]:
model = multilabelSVM()
model.fit(X=data.X_train, y=data.y_train)

In [7]:
# save the model to disk
filename = 'SVM_model.sav'
pickle.dump(model, open(filename, 'wb'))
  
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))

In [8]:
prediction = loaded_model.predict(X=data.X_val)
prediction

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# F1 score for each instrument:

In [13]:
from sklearn.metrics import f1_score
f1_score(y_true=data.y_val, y_pred=prediction, average=None)

array([0.08845209, 0.00947867, 0.06854839, 0.18760659, 0.21695213,
       0.16764706, 0.20285159, 0.18105263, 0.07247494, 0.115     ,
       0.30430622])